### ISSUE TITLE
New Version don't work with Pop-OS! 20.10

### ISSUE THREAD

**Issue by eduardoArgenton** [mymindstorm/gnome-volume-mixer#14]
After the update to the v7 it gives an error when i try to install

**Comment by mymindstorm** [comment]
Could you please provide the error message? What is your gnome shell version? Can you give any output from `journalctl /usr/bin/gnome-shell -f` that references `volume-mixer@evermiss.net`?

**Comment by eduardoArgenton** [comment]
Sorry, apparently was a bug, after restart, it come back to work
