### ISSUE TITLE
No image with some applications

### ISSUE THREAD

**Issue by miguelalt786** [mymindstorm/gnome-volume-mixer#16]
Hello, i don't know if its an bug just for me or to everybody, but some apps logos doesn't load on extension, from what i tested so far the Rhythmbox and Chromium icons doesn't load for me.

![Screenshot from 2021-07-27 14-27-26](https://user-images.githubusercontent.com/69548014/127201010-15fb87ac-cde0-49ad-8121-aae3faa74f96.png)

The Chromium app was installed via Flatpak and the Rhythmbox via Pacman.
I'm using the Gnome 40.3.0 with X11 on Arch with the latest extension upgrade installed.

Thanks in advance.

**Comment by CCaroV** [comment]
I have this same issue on Gnome 41 on Wayland (Fedora 35), and I remember to had it on Gnome 40.1 on Xorg (Fedora 34).
Does someone know how to fix this?

**Comment by mymindstorm** [comment]
This issue stems from the applications providing incorrect icon names to their audio streams. For example, the audio settings in gnome settings will also not be able to show an icon. There isn't much I can do on this end. I've added an option to not show the application icon in v11 to mitigate this.
