### ISSUE TITLE
Add option to hide specific apps

### ISSUE THREAD

**Issue by janosbrodbeck** [mymindstorm/gnome-volume-mixer#3]
Working fine so far, but one feature would be nice: Hide specific apps.

Reason: I'm using PulseEffects as equalizer. And PulseEffects is shown as an own app but practically it is my master volume.

**Comment by mymindstorm** [comment]
Do you mind testing this version? [volume-mixer.zip](https://github.com/mymindstorm/gnome-volume-mixer/files/5211719/volume-mixer.zip)

Install it with `gnome-extensions install -f`

**Comment by janosbrodbeck** [comment]
Re-login was needed so that the new settings menu appeared.
It works! Very nice, thank you :)
