### ISSUE TITLE
On using the Extension with Firefox browser, The volume levels resets.

### ISSUE THREAD

**Issue by aystic** [mymindstorm/gnome-volume-mixer#9]
When I try to increase or decrese the volume on youtube the volume level in the extension resets to a particular volume while on some websites the volume is set to max no matter what you do.
I am using Ubuntu 20.04.2 LTS, GNOME Version 3.36.8

**Comment by mymindstorm** [comment]
What extension version (`gnome-extensions info volume-mixer@evermiss.net`) and Firefox version are you using? Does this also occur when changing the volume level via pavucontrol?

**Comment by aystic** [comment]
![image](https://user-images.githubusercontent.com/54324845/109234565-f2d80880-77f1-11eb-8bbb-e32a60acf974.png)

**Comment by mymindstorm** [comment]
You will need to install pavucontrol to use it.

**Comment by aystic** [comment]
Its not working with pavcontrol installed as well. The volume resets to max after reloading the page on some sites.

**Comment by aystic** [comment]
Its not working with pavucontrol installed as well. The volume resets to max after reloading the page on some sites.

**Comment by mymindstorm** [comment]
If it is not working in pavucontrol, that means that this is either an issue with Firefox itself or pulseaudio.
